CREATE DATABASE IF NOT EXISTS taller_motos CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE taller_motos;

CREATE TABLE IF NOT EXISTS clients (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(120) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bikes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  plate VARCHAR(10) NOT NULL UNIQUE,
  brand VARCHAR(60) NOT NULL,
  model VARCHAR(60) NOT NULL,
  cylinder VARCHAR(20) NULL,
  client_id INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_bikes_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS work_orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  moto_id INT NOT NULL,
  entry_date DATE NOT NULL,
  fault_description TEXT NOT NULL,
  status ENUM('RECIBIDA','DIAGNOSTICO','EN_PROCESO','LISTA','ENTREGADA','CANCELADA') NOT NULL DEFAULT 'RECIBIDA',
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_work_orders_bike FOREIGN KEY (moto_id) REFERENCES bikes(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS work_order_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  work_order_id INT NOT NULL,
  type ENUM('MANO_OBRA','REPUESTO') NOT NULL,
  description VARCHAR(200) NOT NULL,
  count INT NOT NULL,
  unit_value DECIMAL(12,2) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_items_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE,
  CONSTRAINT chk_count_positive CHECK (count > 0),
  CONSTRAINT chk_unit_value_non_negative CHECK (unit_value >= 0)
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('ADMIN','MECANICO') NOT NULL DEFAULT 'MECANICO',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS work_order_status_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  work_order_id INT NOT NULL,
  from_status ENUM('RECIBIDA','DIAGNOSTICO','EN_PROCESO','LISTA','ENTREGADA','CANCELADA') NULL,
  to_status ENUM('RECIBIDA','DIAGNOSTICO','EN_PROCESO','LISTA','ENTREGADA','CANCELADA') NOT NULL,
  note VARCHAR(500) NULL,
  changed_by_user_id INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_history_order_date (work_order_id, created_at DESC),
  CONSTRAINT fk_history_work_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_history_user FOREIGN KEY (changed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
);
